require:
  - rubocop-minitest
  - rubocop-rake

inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Layout/LineLength:
  Max: 180

Metrics/ModuleLength:
  Exclude:
    - lib/pomoru/commands/control.rb

Minitest/MultipleAssertions:
  Max: 4

Naming/VariableNumber:
  CheckMethodNames: false
